import Head from "next/head";
import Link from "next/link";

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="/">
          <h1>HOME</h1>
        </Link>
        <Link href="Post">
          <h1>POSTS</h1>
        </Link>
      </header>

      <main>{children}</main>

      <footer>
        <h1>Page Footer</h1>
      </footer>
    </>
  );
};

export default Layout;
